spring:
  application:
    name: auth-server
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:7001/eureka/ #admin:123456@
  instance:
    prefer-ip-address: true