spring:
  application:
    name: resource-server1
server:
  port: 9011
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:7001/eureka/ #admin:123456@
  instance:
    prefer-ip-address: true