spring:
  application:
    name: zuul-server
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:7001/eureka/ #admin:123456@
  instance:
    prefer-ip-address: true
zuul:
  sensitiveHeaders: Cookie,Set-Cookie #默认是隐私权限信息不传递，导致服务间调用出错